
# DON'T EDIT this file - it is automatically generated by cmake
import os
import sys
# see [StackOverflow](https://stackoverflow.com/a/62613202) on how to automatically show all classes in Docs
sys.path.insert(0, os.path.abspath('..'))  # Source code dir relative to this file

project = 'OTFProfiler'
author = 'OTFProfiler_AUTHOR'
release = '2.0.0'
extensions = [
	'myst_parser',
	'breathe',
    'sphinx.ext.autodoc',  # Core library for html generation from docstrings
    'sphinx.ext.autosummary',  # Create neat summary tables
]
autosummary_generate = True  # Turn on sphinx.ext.autosummary

# Optional: treat .md files as documents
source_suffix = {
	'.rst': 'restructuredtext',
	'.md': 'markdown',
}

# pull in XML from Doxygen
breathe_projects = {
    'OTFProfiler' : '/home/alex/Documents/Work/ra_shk/otf2_cli_profile/build/docs/doxygen/xml'
}
breathe_default_project = 'OTFProfiler'
